//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoriosComputo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesorio
    {
        public int id { get; set; }
        public string strNombre { get; set; }
        public string strColor { get; set; }
        public Nullable<int> idMarca { get; set; }
        public Nullable<int> idModelo { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idMaterial { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Material Material { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
